# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"I:/Cosas/Dev-CppPortable/App/devcpp/lib" -lbgi  -lgdi32  -lcomdlg32  -luuid  -loleaut32  -lole32   
INCS =  -I"I:/Cosas/Dev-CppPortable/App/devcpp/include" 
CXXINCS =  -I"I:/Cosas/Dev-CppPortable/App/devcpp/lib/gcc/mingw32/3.4.2/include"  -I"I:/Cosas/Dev-CppPortable/App/devcpp/include/c++/3.4.2/backward"  -I"I:/Cosas/Dev-CppPortable/App/devcpp/include/c++/3.4.2/mingw32"  -I"I:/Cosas/Dev-CppPortable/App/devcpp/include/c++/3.4.2"  -I"I:/Cosas/Dev-CppPortable/App/devcpp/include" 
BIN  = Project1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Project1.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
